name: Scala CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Download and install sbt
      run: |
        curl -L https://github.com/sbt/sbt/releases/download/v1.5.5/sbt-1.5.5.tgz | tar xz -C /tmp && \
        sudo mv /tmp/sbt /usr/local

    - name: Build and Run
      run: /usr/local/sbt/bin/sbt run

    - name: Build and Run
      run: /usr/local/sbt/bin/sbt "runMain HelloWorld"
